# Generated by Django 5.2.1 on 2025-05-14 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
    ]
