from django.urls import path
from . import views

app_name = 'marketplace'

urlpatterns = [
    path('', views.home, name='home'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('cart/', views.cart, name='cart'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('orders/', views.order_history, name='orders'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('initiate_payment/<int:cart_item_id>/', views.initiate_payment, name='initiate_payment'),
    path('seller/dashboard/', views.seller_dashboard, name='seller_dashboard'),
    path('seller/product/add/', views.add_product, name='add_product'),
    path('seller/product/edit/<int:product_id>/', views.edit_product, name='edit_product'),
    path('seller/product/delete/<int:product_id>/', views.delete_product, name='delete_product'),
    path('search/', views.search_products, name='search_products'),
    path('checkout/', views.checkout, name='checkout'),
    path('order-confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),
    path('mpesa/callback/', views.mpesa_callback, name='mpesa_callback'),
    path('add-review/<int:product_id>/', views.add_review, name='add_review'),
    path('search-autocomplete/', views.search_autocomplete, name='search_autocomplete'),
    path('set-theme/', views.set_theme, name='set_theme'),
    path('paypal-success/', views.paypal_success, name='paypal_success'),
    path('paypal-cancel/', views.paypal_cancel, name='paypal_cancel'),
    path('payment-success/', views.payment_success, name='payment_success'),
    path('process-card-payment/', views.process_card_payment, name='process_card_payment'),
    path('initiate-paypal-payment/', views.initiate_paypal_payment, name='initiate_paypal_payment'),
    path('about/', views.about, name='about'),
    path('careers/', views.careers, name='careers'),
    path('blog/', views.blog, name='blog'),
    path('faqs/', views.faqs, name='faqs'),
    path('shipping-returns/', views.shipping_returns, name='shipping-returns'),
    path('track-order/', views.track_order, name='track_order'),
    path('privacy-policy/', views.privacy_policy, name='privacy-policy'),
    path('terms-of-service/', views.terms_of_service, name='terms-of-service'),
    path('refund-policy/', views.refund_policy, name='refund-policy'),
]